Do
```
python3 main.py
```
to run. The bug was found while using python3.5.6 and pysc2.0